services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db                       
      - ./mongod.conf:/etc/mongod.conf          
      - ./certs/mongodb.pem:/etc/ssl/mongodb.pem 
      - ./certs/mongodb-ca.pem:/etc/ssl/mongodb-ca.pem 
    command: ["mongod", "--config", "/etc/mongod.conf"]
    environment:
      - GLIBC_TUNABLES=glibc.pthread.rseq=0

  api:
    build: .
    container_name: node_app
    ports:
      - 5000:5000
    depends_on:
      - mongo_db
    environment:
      PORT: 5000
      MONGODB_URL: mongodb://mongo_db:27017/EShop
      JWT_SECRET: mysecret

volumes:
  mongo_db: {}
